### ISSUE TITLE
No sparse and very sparse mazes

### ISSUE THREAD

**Issue by WangChen100** [alex-petrenko/curious-rl#1]
Hi Alex, it raises error, " No registered env with id: VizdoomMyWayHomeSparse-v0", when I test sparse and very sparse maze.

Is there anything wrong when I install the packages?

Thank you very much. Waiting for your reply.

**Comment by WangChen100** [comment]
![Screenshot from 2019-06-13 20-50-32](https://user-images.githubusercontent.com/30588895/59434007-44254600-8e1d-11e9-8b1d-684c13a63a20.png)

**Comment by alex-petrenko** [comment]
Hmm... maybe vizdoomgym package didn't install properly. I will look at it!

**Comment by alex-petrenko** [comment]
Can you pull the latest commit and try again?
Some package versions weren't locked in Pipfile and presumably your installation failed, that's why gym cannot detect envs in vizdoomgym.

I suggest you kill your pipenv with `pipenv --rm` and then follow updated instruction:

```
pipenv install
pipenv shell
python -m algorithms.curious_a2c.train_curious_a2c --env=doom_maze_very_sparse
```

It worked for me now with a fresh installation on a new machine

**Comment by WangChen100** [comment]
Thank you very much for your help.

I have another question. When I generate the wad file for building maze by myself, how can I set the initialized location and the goal location?

In other words, do your know how to generate maze_sparse.wad and maze_very_sparse.wad? It seems that we can build the wad file of mazes by omgifol module. But unfortunately I don't know how to set agent's original location and goal.

Could you offer some clues? Thanks.
